CREATE TABLE spro.daegu (
  idx INT NOT NULL,
  name VARCHAR(45) NULL,
  location VARCHAR(45) NULL,
  code1 VARCHAR(45) NULL,
  code1_name VARCHAR(45) NULL,
  code2VARCHAR(45) NULL,
  code2_name VARCHAR(45) NULL,
  code_3 VARCHAR(45) NULL,
  code4 VARCHAR(45) NULL,
  code4_name varchar(45) null,
  code_sido VARCHAR(45) NULL,
  code_sidoname varchar(45) null,
  code_gu VARCHAR(45) NULL,
  code_guname varchar(45) null,
  code_dong VARCHAR(45) NULL,
  code_dongname varchar(45) null,
  code_legar VARCHAR(45) NULL,
  code_legarname varchar(45) null,
  code_jibun VARCHAR(45) NULL,
  code_jibunname varchar(45) null,
  code_gubun VARCHAR(45) NULL,
  code_gubunname varchar(45) null,
  jibon_bon varchar(45) null,
  jibon_bu varchar(45) null,
  jibon_addr varchar(45) null,
  code_doro VARCHAR(45) NULL,
  code_doroname varchar(45) null,
  building_bon varchar(45) null,
  building_bu varchar(45) null,
  building_num varchar(45) null,
  building_name varchar(45) null,
  doro_addr varchar(45) null,
  oldzip varchar(45) null,
  newzip varchar(45) null,
  donginfo varchar(45) null,
  floorinfo varchar(45) null,
  hoinfo varchar(45) null,
  longitude varchar(45) null,
  latitude varchar(45) null,
  PRIMARY KEY (idx))
COMMENTcovid = 상가업소번호|상호명|지점명|상권업종대분류코드|상권업종대분류명|상권업종중분류코드
		|상권업종중분류명|상권업종소분류코드|표준산업분류코드|표준산업분류명|시도코드
        |시도명|시군구코드|시군구명|행정동코드|행정동명|법정동코드|법정동명|지번코드
        |대지구분코드|대지구분명|지번본번지|지번부번지|지번주소|도로명코드
        |도로명|건물본번지|건물부번지|건물관리번호|건물명|도로명주소
        |구우편번호|신우편번호|동정보|층정보|호정보|경도|위도
;
drop table daegu;
select * from daegu;

INSERT INTO daegu
(idx,
name`INSERT INTO `spro`.`daegu`
(`idx`,
`name`,
`location`,
`code1`,
`code1_name`,
`code2`,
`code2_name`,
`code_3`,
`code4`,
`code4_name`,
`code_sido`,
`code_sidoname`,
`code_gu`,
`code_guname`,
`code_dong`,
`code_dongname`,
`code_legar`,
`code_legarname`,
`code_jibun`,
`code_jibunname`,
`code_gubun`,
`code_gubunname`,
`jibon_bon`,
`jibon_bu`,
`jibon_addr`,
`code_doro`,
`code_doroname`,
`building_bon`,
`building_bu`,
`building_num`,
`building_name`,
`doro_addr`,
`oldzip`,
`newzip`,
`donginfo`,
`floorinfo`,
`hoinfo`,
`longitude`,
`latitude`)
VALUES
(<{idx: }>,
<{name: }>,
<{location: }>,
<{code1: }>,
<{code1_name: }>,
<{code2: }>,
<{code2_name: }>,
<{code_3: }>,
<{code4: }>,
<{code4_name: }>,
<{code_sido: }>,
<{code_sidoname: }>,
<{code_gu: }>,
<{code_guname: }>,
<{code_dong: }>,
<{code_dongname: }>,
<{code_legar: }>,
<{code_legarname: }>,
<{code_jibun: }>,
<{code_jibunname: }>,
<{code_gubun: }>,
<{code_gubunname: }>,
<{jibon_bon: }>,
<{jibon_bu: }>,
<{jibon_addr: }>,
<{code_doro: }>,
<{code_doroname: }>,
<{building_bon: }>,
<{building_bu: }>,
<{building_num: }>,
<{building_name: }>,
<{doro_addr: }>,
<{oldzip: }>,
<{newzip: }>,
<{donginfo: }>,
<{floorinfo: }>,
<{hoinfo: }>,
<{longitude: }>,
<{latitude: }>);
,
`location`,
`code1`,
`code1_name`,
`code2`,
`code2_name`,
`code_3`,
`code4`,
`code4_name`,
`code_sido`,
`code_sidoname`,
`code_gu`,
`code_guname`,
`code_dong`,
`code_dongname`,
`code_legar`,
`code_legarname`,
`code_jibun`,
`code_jibunname`,
`code_gubun`,
`code_gubunname`,
`jibon_bon`,
`jibon_bu`,
`jibon_addr`,
`code_doro`,
`code_doroname`,
`building_bon`,
`building_bu`,
`building_num`,
`building_name`,
`doro_addr`,
`oldzip`,
`newzip`,
`donginfo`,
`floorinfo`,
`hoinfo`,
`longitude`,
`latitude`)
VALUES
(<{idx: }>,
<{name: }>,
<{location: }>,
<{code1: }>,
<{code1_name: }>,
<{code2: }>,
<{code2_name: }>,
<{code_3: }>,
<{code4: }>,
<{code4_name: }>,
<{code_sido: }>,
<{code_sidoname: }>,
<{code_gu: }>,
<{code_guname: }>,
<{code_dong: }>,
<{code_dongname: }>,
<{code_legar: }>,
<{code_legarname: }>,
<{code_jibun: }>,
<{code_jibunname: }>,
<{code_gubun: }>,
<{code_gubunname: }>,
<{jibon_bon: }>,
<{jibon_bu: }>,
<{jibon_addr: }>,
<{code_doro: }>,
<{code_doroname: }>,
<{building_bon: }>,
<{building_bu: }>,
<{building_num: }>,
<{building_name: }>,
<{doro_addr: }>,
<{oldzip: }>,
<{newzip: }>,
<{donginfo: }>,
<{floorinfo: }>,
<{hoinfo: }>,
<{longitude: }>,
<{latitude: }>);
